#

version: '2'

volumes:
  peer0.provider.policiamilitar.sp.gov.br:
  peer1.provider.policiamilitar.sp.gov.br:
  peer0.consumer.policiamilitar.sp.gov.br:
  peer1.consumer.policiamilitar.sp.gov.br:
  orderer.policiamilitar.sp.gov.br:
  orderer1.policiamilitar.sp.gov.br:

networks:
  dpNetwork:
    external: 
        name: network_dpNetwork
      
services:
  orderer.policiamilitar.sp.gov.br:
    extends:
      file: docker-compose-base.yaml
      service: orderer.policiamilitar.sp.gov.br
    container_name: orderer.policiamilitar.sp.gov.br
    networks:
      - dpNetwork
      
  orderer1.policiamilitar.sp.gov.br:
    extends:
      file: docker-compose-base.yaml
      service: orderer1.policiamilitar.sp.gov.br
    container_name: orderer1.policiamilitar.sp.gov.br
    networks:
      - dpNetwork   
      
  peer0.provider.policiamilitar.sp.gov.br:
    container_name: peer0.provider.policiamilitar.sp.gov.br
    extends:
      file: peer-base.yaml
      service: peer-base
    hostname: peer0.provider.policiamilitar.sp.gov.br
    environment: 
      - CORE_PEER_ID=peer0.provider.policiamilitar.sp.gov.br
      - CORE_PEER_ADDRESS=peer0.provider.policiamilitar.sp.gov.br:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.provider.policiamilitar.sp.gov.br:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=ProviderMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=192.168.1.33:5984
      ###############
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.provider.policiamilitar.sp.gov.br:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.provider.policiamilitar.sp.gov.br:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.provider.policiamilitar.sp.gov.br:7051
      ##############
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer0.provider.policiamilitar.sp.gov.br/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer0.provider.policiamilitar.sp.gov.br/tls/:/etc/hyperledger/fabric/tls
        - peer0.provider.policiamilitar.sp.gov.br:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - dpNetwork

  peer1.provider.policiamilitar.sp.gov.br:
    container_name: peer1.provider.policiamilitar.sp.gov.br
    extends:
      file: peer-base.yaml
      service: peer-base
    hostname: peer1.provider.policiamilitar.sp.gov.br
    environment: 
      - CORE_PEER_ID=peer1.provider.policiamilitar.sp.gov.br
      - CORE_PEER_ADDRESS=peer1.provider.policiamilitar.sp.gov.br:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
      - CORE_PEER_CHAINCODEADDRESS=peer1.provider.policiamilitar.sp.gov.br:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=192.168.1.33:6984
      ##################
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.provider.policiamilitar.sp.gov.br:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.provider.policiamilitar.sp.gov.br:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.provider.policiamilitar.sp.gov.br:8051
      #######
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb1
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer1.provider.policiamilitar.sp.gov.br/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer1.provider.policiamilitar.sp.gov.br/tls/:/etc/hyperledger/fabric/tls
        - peer1.provider.policiamilitar.sp.gov.br:/var/hyperledger/production
    ports:
      - 8051:7051
    networks:
      - dpNetwork

  peer0.consumer.policiamilitar.sp.gov.br:
    container_name: peer0.consumer.policiamilitar.sp.gov.br
    extends:
      file: peer-base.yaml
      service: peer-base
    hostname: peer0.consumer.policiamilitar.sp.gov.br
    environment:
      - CORE_PEER_ID=peer0.consumer.policiamilitar.sp.gov.br
      - CORE_PEER_ADDRESS=peer0.consumer.policiamilitar.sp.gov.br:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.policiamilitar.sp.gov.br:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=192.168.1.33:7984
      ##################
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.consumer.policiamilitar.sp.gov.br:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.policiamilitar.sp.gov.br:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.policiamilitar.sp.gov.br:9051
      #######
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/consumer.policiamilitar.sp.gov.br/peers/peer0.consumer.policiamilitar.sp.gov.br/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consumer.policiamilitar.sp.gov.br/peers/peer0.consumer.policiamilitar.sp.gov.br/tls/:/etc/hyperledger/fabric/tls
        - peer0.consumer.policiamilitar.sp.gov.br:/var/hyperledger/production
    depends_on:
      - couchdb2
    ports:
      - 9051:7051
    networks:
      - dpNetwork

  peer1.consumer.policiamilitar.sp.gov.br:
    container_name: peer1.consumer.policiamilitar.sp.gov.br
    extends:
      file: peer-base.yaml
      service: peer-base
    hostname: peer1.consumer.policiamilitar.sp.gov.br
    environment:
      - CORE_PEER_ID=peer1.consumer.policiamilitar.sp.gov.br
      - CORE_PEER_ADDRESS=peer1.consumer.policiamilitar.sp.gov.br:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
      - CORE_PEER_CHAINCODEADDRESS=peer1.consumer.policiamilitar.sp.gov.br:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=192.168.1.33:8984
      ##################
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.consumer.policiamilitar.sp.gov.br:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.policiamilitar.sp.gov.br:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.policiamilitar.sp.gov.br:10051
      #######
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb3
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/consumer.policiamilitar.sp.gov.br/peers/peer1.consumer.policiamilitar.sp.gov.br/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consumer.policiamilitar.sp.gov.br/peers/peer1.consumer.policiamilitar.sp.gov.br/tls/:/etc/hyperledger/fabric/tls
        - peer1.consumer.policiamilitar.sp.gov.br:/var/hyperledger/production
    networks:
      - dpNetwork
        
    ports:
      - 10051:7051

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.provider.policiamilitar.sp.gov.br:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer0.provider.policiamilitar.sp.gov.br/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer0.provider.policiamilitar.sp.gov.br/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/peers/peer0.provider.policiamilitar.sp.gov.br/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/provider.policiamilitar.sp.gov.br/users/Admin@provider.policiamilitar.sp.gov.br/msp
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/ordererOrganizations/policiamilitar.sp.gov.br/orderers/orderer.policiamilitar.sp.gov.br/msp/tlscacerts/tlsca.policiamilitar.sp.gov.br-cert.pem
      - ORDERER1_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/ordererOrganizations/policiamilitar.sp.gov.br/orderers/orderer1.policiamilitar.sp.gov.br/msp/tlscacerts/tlsca.policiamilitar.sp.gov.br-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/        
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/        
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        - ./commands:/opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - orderer.policiamilitar.sp.gov.br
      - peer0.provider.policiamilitar.sp.gov.br
      - peer1.provider.policiamilitar.sp.gov.br
      - peer0.consumer.policiamilitar.sp.gov.br
      - peer1.consumer.policiamilitar.sp.gov.br
    networks:
      - dpNetwork
    
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:0.4.18
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - dpNetwork

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:0.4.18
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - dpNetwork

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:0.4.18
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"
    networks:
      - dpNetwork

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:0.4.18
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      - dpNetwork

  zookeeper0.policiamilitar.sp.gov.br:
    image: hyperledger/fabric-zookeeper:0.4.18
    container_name: zookeeper0.policiamilitar.sp.gov.br
    restart: always
    hostname: zookeeper0.policiamilitar.sp.gov.br
    environment:  
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - dpNetwork       

  kafka0.policiamilitar.sp.gov.br:
    image: hyperledger/fabric-kafka:0.4.18
    container_name: kafka0.policiamilitar.sp.gov.br
    hostname: kafka0.policiamilitar.sp.gov.br
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.33:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.33:9092
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      - dpNetwork         
    depends_on:
      - zookeeper0.policiamilitar.sp.gov.br
     